CREATE VIEW GetAlarmHistory
AS
SELECT
ALARM.AlarmId,
ALARMCONFIGURATION.AlarmName,
ALARMCONFIGURATION.AlarmDescription,
ALARM.AlarmTimeStamp,
ALARM.Value,
ALARM.AckTimeStamp
FROM ALARM
INNER JOIN ALARMCONFIGURATION ON ALARM.AlarmConfigurationId = ALARMCONFIGURATION.AlarmConfigurationId
