CREATE VIEW GetAlarms
AS
SELECT
ALARM.AlarmId,
ALARMCONFIGURATION.AlarmName,
ALARMCONFIGURATION.AlarmDescription,
ALARM.AlarmTimeStamp,
ALARM.Value,
ACKNOWLEDGE.AckStatus
--ACKNOWLEDGE.AckTimeStamp
FROM ALARM
INNER JOIN ALARMCONFIGURATION ON ALARM.AlarmConfigurationId = ALARMCONFIGURATION.AlarmConfigurationId
INNER JOIN ACKNOWLEDGE ON ALARM.AcknowledgeId = ACKNOWLEDGE.AcknowledgeId