CREATE VIEW GetAlarmConfigurations
AS
SELECT
ALARMCONFIGURATION.AlarmConfigurationId,
ALARMCONFIGURATION.AlarmName,
ALARMCONFIGURATION.AlarmDescription,
ALARMCONFIGURATION.AlarmLowerLimit,
ALARMCONFIGURATION.AlarmUpperLimit,
ALARMLEVEL.AlarmLevel,
TAGCONFIGURATION.TagName
FROM ALARMCONFIGURATION
INNER JOIN ALARMLEVEL ON ALARMCONFIGURATION.AlarmLevelId = ALARMLEVEL.AlarmLevelId
INNER JOIN TAGCONFIGURATION ON ALARMCONFIGURATION.TagId = TAGCONFIGURATION.TagId
