CREATE VIEW GetAlarmConfigurations
AS
SELECT
ALARMCONFIGURATION.AlarmConfigurationId,
ALARMCONFIGURATION.Name,
ALARMCONFIGURATION.Description,
ALARMLEVEL.Level,
ALARMLEVEL.Description
FROM ALARMCONFIGURATION
