CREATE VIEW GetTagConfigurations
AS
SELECT 
TAGDATA.TagDataId,
TAGDATA.TagValue,
TAGDATA.TagStatus,
TAGDATA.TagTimestamp,
TAGCONFIGURATION.TagId,
TAGCONFIGURATION.TagName
FROM TAGDATA
INNER JOIN TAGCONFIGURATION ON TAGDATA.TagId = TAGCONFIGURATION.TagId